# docker-compose.yml
version: '3.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - wiremock
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      APP_PORT: ${APP_PORT}
      DB_PORT: ${DB_PORT}
      CONTRIBUINTES_API_HOST: wiremock
      CONTRIBUINTES_API_PORT: 8081

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8080

  db:
    image: postgres:16
    container_name: gestao_contribuicao_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  wiremock:
    image: wiremock/wiremock
    ports:
      - "8081:8081"
    volumes:
      - ./stubs:/home/wiremock
    command: --port 8081

volumes:
  postgres_data:
